name = "makelucky-metrics"
main = "src/worker.js"
compatibility_date = "2024-10-01"

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "CounterDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["CounterDO"]
