name: Deploy to Root GitHub Pages (idobee.github.io)

on:
  workflow_dispatch:
    inputs:
      external_repository:
        description: External repo to publish (owner/repo)
        required: false
        default: idobee/idobee.github.io
      publish_branch:
        description: Branch to publish to (main or master)
        required: false
        default: main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Prepare .env.production (Secrets/Variables fallback)
        run: |
          CLIENT_ID="${{ secrets.VITE_GOOGLE_ADSENSE_CLIENT_ID }}"
          if [ -z "$CLIENT_ID" ]; then CLIENT_ID="${{ vars.VITE_GOOGLE_ADSENSE_CLIENT_ID }}"; fi
          SLOT_ID="${{ secrets.VITE_GOOGLE_ADSENSE_SLOT_ID }}"
          if [ -z "$SLOT_ID" ]; then SLOT_ID="${{ vars.VITE_GOOGLE_ADSENSE_SLOT_ID }}"; fi
          echo "VITE_GOOGLE_ADSENSE_CLIENT_ID=$CLIENT_ID" >> .env.production
          echo "VITE_GOOGLE_ADSENSE_SLOT_ID=$SLOT_ID" >> .env.production
          # Debug presence only (do not print secrets)
          if [ -n "$CLIENT_ID" ]; then echo "CLIENT_ID: present"; else echo "CLIENT_ID: MISSING"; fi
          if [ -n "$SLOT_ID" ]; then echo "SLOT_ID: present"; else echo "SLOT_ID: MISSING"; fi

      - name: Check external repository exists and PAT permissions
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          EXTERNAL_REPO: ${{ inputs.external_repository }}
        run: |
          set -e
          if [ -z "$EXTERNAL_REPO" ]; then EXTERNAL_REPO="idobee/idobee.github.io"; fi
          CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$EXTERNAL_REPO)
          if [ "$CODE" != "200" ]; then
            echo "::error::External repository '$EXTERNAL_REPO' not found or no access.\n- Create repo named 'idobee.github.io' (Public)\n- Ensure PAT has Contents: Read and write to that repo.\n- Then re-run this workflow."
            exit 1
          fi

      - name: Build for root site (base=/)
        run: |
          # TypeScript compile and Vite build with root base
          ./node_modules/.bin/tsc -p tsconfig.json
          ./node_modules/.bin/vite build --base=/

      - name: Add SPA fallback (404.html) and .nojekyll
        run: |
          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Deploy to external repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: ${{ inputs.external_repository }}
          publish_branch: ${{ inputs.publish_branch }}
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "Deploy MakeLucky to root site: ${{ github.sha }} (repo=${{ inputs.external_repository }}, branch=${{ inputs.publish_branch }})"
